###########################################
# GLOBAL
###########################################
vagrant_user: "vagrant"
path_home: /home/vagrant

###########################################
# DOCKER VARIABLES
###########################################
install_docker: True # se settata a true docker verrà installato , se non si vuole installare docker settare su false

###########################################
# MICRO8SK VARIABLES
###########################################
install_microk8s: false # se settata a true microk8s verrà installato , se non si vuole installare microk8s settare su false

###########################################
# PORTAINER VARIABLES
###########################################
install_portainer: True

portainer_container_name: portainer
portainer_container_image: portainer/portainer-ce
portainer_container_ports: 9000:9000
portainer_container_config_volume: /var/run/docker.sock:/var/run/docker.sock
portainer_container_data_volume: /home/vagrant/portainer:/data

###########################################
# MINIKUBE VARIABLES
###########################################
install_minikube: True #se settata a true minikube verrà installato , se non si vuole installare minikube settare su false

packages:
  - curl
  - apt-transport-https
  - conntrack
  - wget
  - net-tools
  - git

###########################################
# HELM VARIABLES
###########################################
install_helm: True #se settata a true helm verrà installato , se non si vuole installare helm settare su false

get_helm_url: https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
path_helm_installation: "{{ path_home }}/helm"
kubeconfig_path: ~/.kube/config

helm_charts:
  - name: mattermost
    chart_repo_url: "https://helm.mattermost.com"
    chart_ref: "mattermost-team-edition"
    release_namespace: mattermost
    create_namespace: true
    state: present
    values_files:
      - "{{ path_helm_installation }}/mattermost_values.yaml"
  - name: ingress-nginx
    chart_repo_url: "https://charts.bitnami.com/bitnami"
    chart_ref: "nginx-ingress-controller"
    release_namespace: ingress
    create_namespace: true
    state: present
    values_files:
      - "{{ path_helm_installation }}/ingress_nginx_values.yaml"