# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.ssh.insert_key = true

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "bento/ubuntu-22.04"
        ubuntu.vm.hostname = "ubuntu"
        ubuntu.vm.network "public_network" #, ip: 123.34.123.34
    end

    config.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu_server_22-04"
      vb.gui = true
      vb.memory = 4096
      vb.cpus = 2
      vb.check_guest_additions = false
    end
  
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "Ansible/playbooks/configure_ubuntu_server.yml"
    end  

end
  