# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    config.ssh.insert_key = true
    #config.ssh.private_key_path= "ssh-key_vm-avanade-marco.pem"

    config.vm.define "ubuntu" do |ubuntu|
        ubuntu.vm.box = "ubuntu/bionic64"
        ubuntu.vm.hostname = "ubuntu"
        ubuntu.vm.network "public_network" #, ip: 123.34.123.34
    end

    config.vm.disk :disk, size: "20GB", primary: true

    config.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu_vm"
      vb.gui = true
      vb.memory = 4096
      vb.cpus = 2
      vb.check_guest_additions = false
    end
  
    config.vm.provision "shell", path: "install_ansible.sh"
    #config.vm.provision "shell", path: "../../Scripts/install_retropie.sh"
  
    config.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "playbook.yml"
    end  

end
  